import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { Button } from "@/components/ui/button";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// 헤더
const Header = () => {
  return (
    <header className="top-0 z-50 w-full items-center backdrop-blur flex flex-row justify-center">
      {/* 프로젝트 이름 */}
      <div className="flex-1 flex items-center justify-start p-4 my-7">
      </div>
      <div className="flex items-center justify-center p-4 my-7">
        <Link href="/">
          <span className="font-extrabold text-6xl">프로젝트 이름</span>
        </Link>
      </div>
      {/* 로그인 버튼 */}
      <div className="flex-1 flex items-center justify-end p-4 my-7">
        <Link href="/login">
          <Button>로그인</Button>
        </Link>
      </div>
    </header>
  );
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
